### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by johnbrett** [tkh44/emotion-create-react-app-example#2]
Hi @tkh44 big thanks for providing this repo!

Just ran into an issue after cloning this and install deps: 

`npm start` runs just fine, but I get the following when trying to run `npm test`:

```
 FAIL  src/App.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'join' of undefined

      at hashArray (node_modules/emotion/lib/hash.js:11:16)
      at Object.keyframes (node_modules/emotion/lib/index.js:95:34)
      at Object.<anonymous> (src/App.js:6:38)
      at Object.<anonymous> (src/App.test.js:3:12)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.124s
Ran all test suites.
```
Any ideas on how to debug this? Are you seeing this too?

**Comment by tkh44** [comment]
Let me try to reproduce.

**Comment by tkh44** [comment]
I was able to reproduce.
![image](https://user-images.githubusercontent.com/662750/30299915-2e8b7d0c-970f-11e7-905e-ba2d9d5c4bb8.png)

**Comment by tkh44** [comment]
Fixed with https://github.com/tkh44/emotion-create-react-app-example/commit/6dd83b616c8899bd700e9e163e9c4483ca7bec2d

Enjoy! Let me know if you have any other issues @johnbrett

**Comment by johnbrett** [comment]
Ah, thanks for the quick response on  this! I'm getting a different error now, but probably something similar to before, seems to still be an issue with keyframes:
```
 FAIL  src/App.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'apply' of undefined

      at Object.keyframes (node_modules/emotion/dist/index.cjs.js:317:31)
      at Object.<anonymous> (src/App.js:6:38)
      at Object.<anonymous> (src/App.test.js:3:12)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.934s
Ran all test suites.
```

(thanks for the help on this btw!)

**Comment by tkh44** [comment]
It *looks* like an emotion version mismatch. Maybe try a fresh node_modules. I'll take a look and see if I can reproduce.

**Comment by johnbrett** [comment]
yep I tried a fresh install node_modules, but still the same issue. It's a strange one, I tried looking through at the emotion internals but didn't make much progress.

**Comment by tkh44** [comment]
My handy friend `jest --resetModules` fixes this.

**Comment by tkh44** [comment]
This was a fun one. All that was needed to fix it was adding a babelrc file in the project that defines emotion as a plugin.

https://github.com/tkh44/emotion-create-react-app-example/commit/49c481d56fc41540c07cbb11ae8d67aae2c107f2#diff-e56633f72ecc521128b3db6586074d2c

I'm guessing that Jest has the same babel config as CRA and they do not expect other Babel plugins. Adding emotion to a babelrc file gives Jest the hint it needs.

**Comment by johnbrett** [comment]
ah! I don't think I would have caught that anyway! That's working for me now, thanks for the help on this!

**Comment by tkh44** [comment]
No problem! Enjoy emotion. If you have any questions you can usually find me over on the slack channel ->  https://emotion.now.sh
